export const STORAGE_KEYS = {
  CAMPAIGN_DATA: "ytstudio_campaign_data",
  CURRENT_INDEX: "ytstudio_current_index",
  COMPLETED_CAMPAIGNS: "ytstudio_completed_campaigns",
  AUTO_CLICK_ENABLED: "ytstudio_auto_click_enabled",
  LAST_UPLOAD_STATUS: "lastUploadStatus",
  UPLOAD_SUCCESS_STATUS: "ytstudio_upload_success_status",
  CAMPAIGN_REGIONS: "ytstudio_campaign_regions",
  CAMPAIGN_TYPES: "ytstudio_campaign_types",
  DATE_RANGE: "ytstudio_date_range",
  WORKFLOW_PAUSED: "ytstudio_workflow_paused",
  BUTTONS_VISIBLE: "ytstudio_buttons_visible",
  SHEET_ID: "ytstudio_sheet_id",
  SHEET_TAB_NAME: "ytstudio_sheet_tab_name",
  DATE_QUEUE: "ytstudio_date_queue",
  CURRENT_DATE_INDEX: "ytstudio_current_date_index",
  COMPLETED_DATES: "ytstudio_completed_dates",
} as const;
