export const STORAGE_KEYS = {
  CAMPAIGN_DATA: "naversa_campaign_data",
  CURRENT_INDEX: "naversa_current_index",
  COMPLETED_CAMPAIGNS: "naversa_completed_campaigns",
  AUTO_CLICK_ENABLED: "naversa_auto_click_enabled",
  LAST_UPLOAD_STATUS: "lastUploadStatus",
  UPLOAD_SUCCESS_STATUS: "naversa_upload_success_status",
  CAMPAIGN_REGIONS: "naversa_campaign_regions",
  CAMPAIGN_TYPES: "naversa_campaign_types",
  DATE_RANGE: "naversa_date_range",
  WORKFLOW_PAUSED: "naversa_workflow_paused",
  BUTTONS_VISIBLE: "naversa_buttons_visible",
  SHEET_ID: "naversa_sheet_id",
  SHEET_TAB_NAME: "naversa_sheet_tab_name",
  DATE_QUEUE: "naversa_date_queue",
  CURRENT_DATE_INDEX: "naversa_current_date_index",
  COMPLETED_DATES: "naversa_completed_dates",
} as const;
